### ISSUE TITLE
本地项目是不能使用chatgpt和视频解析是吗

### ISSUE THREAD

**Issue by 0x083X** [P1kaj1uu/ChatGPT-Video-Parsing#10]
(是因为没有接口吗😂)
还有一些questions。-----
网站地址的视频解析，有些解析接口会跳出来debbuger，有些解析显示的不是相同的电影，比如我想看爱奇异的流浪地球2,它解析出来的是蜡笔小新图片
![截图 2023-05-16 09-11-02](https://github.com/P1kaj1uu/VIP-Video-Parsing/assets/115934135/ba7430ed-3a7c-4e68-816c-43534971a7a3)
但是有些接口还是可以working的，解析出来视频的清晰度比一些油猴插件的都要高🤩

**Comment by 0x083X** [comment]
https://www.iqiyi.com/v_1yzsojq1cg8.html?vfrm=pcw_dianying&vfrmblk=711219_dianying_fyb&vfrmrst=711219_dianying_fyb_float_video_area2
这个是我放进去的解析地址(爱奇异的流浪地球2,爱奇异的解析接口可以使用，前面的都不太行。应该是属于接口的问题吧。。🫠)

**Comment by P1kaj1uu** [comment]
本地代仓里的视频解析接口和chatpgt的接口我做了处理不对外展示，理解下谢谢🙏。部署服务器的那个版本gpt可用的同时无需再代理和APIkey，后续也会添加更多功能和进一步优化；针对视频解析，我提供了多个能用的解析方式接口，理论上第一个首推超推荐那个能满足解析绝大多数的，如果第一个解析不行可以尝试换下面其他的解析方式接口试试，对于解析弹出打断点可能是你按了f12（也可能是我代码问题我有空再排查下稍等），对于解析视频结果不对应的问题后续我想办法改善。感谢你的支持！

**Comment by 0x083X** [comment]
出现打断点应该是我按了f12的关系,我刚刚又试了一遍。

**Comment by zqeeeee** [comment]
怎么访问部署服务器的那个版本

**Comment by P1kaj1uu** [comment]
> 

服务器被挖矿攻击过，不展示公网ip了，具体访问地址私我qq邮箱发送
