### ISSUE TITLE
按照wiki部署完毕访问出现错误。

### ISSUE THREAD

**Issue by lukemin** [P1kaj1uu/ChatGPT-Video-Parsing#17]
DONE  Compiled successfully in 56910ms                                                                                                                                                  1:06:01 PM

  App running at:
  - Local:   http://localhost:8080/ 
  - Network: unavailable

  Note that the development build is not optimized.
  To create a production build, run npm run build.

访问 提示Invalid Host header

**Comment by P1kaj1uu** [comment]
vue.config.js加上这个试试呢
```javascript
devServer: {
  disableHostCheck: true,
}
```
或者
```javascript
devServer: {
  historyApiFallback: true,
  allowedHosts: 'all',
}
```

**Comment by lukemin** [comment]
`const HtmlWebpackPlugin = require('html-webpack-plugin')
const packageJson = require('./package.json')

module.exports = {
  devServer: {
    historyApiFallback: true,
    allowedHosts: 'all',
    proxy: {
      '/api': {
        target: 'https://api.fanyi.baidu.com',
        changeOrigin: true,
        pathRewrite: {
          '^/api': '/api'
        }
      }
    }
  },
}`
修改成上面的可以了

**Comment by lukemin** [comment]
但是chatgpt好像不能用。
发送什么信息都是:
宝，我出错啦，这个问题我也不知道该怎么回答你呢，要不你慢一点，容我再想一想~（建议：清空会话记录试试...

**Comment by P1kaj1uu** [comment]
本地代仓里面gpt代码不是最新的，接口没放进去

**Comment by P1kaj1uu** [comment]
最新版本部署在了服务器上，github上最新代码我还没push上去

**Comment by lukemin** [comment]
我给你qq邮箱发邮件了，试用一下。
